export const products = [

  // ══════════════════════════════════════════════════════
  // BRACELETS (15 items)
  // ══════════════════════════════════════════════════════
  {
    id: 101,
    name: "Meenakari Bangle Set (6 pcs)",
    category: "Bracelet",
    subCategory: "Bangle",
    price: 1799,
    originalPrice: 2200,
    discount: 18,
    rating: 5.0,
    reviews: 62,
    stock: 10,
    isNew: false,
    isBestSeller: true,
    description: "Set of 6 Meenakari bangles with vibrant enamel work and kundan border. Available in sizes 2.4, 2.6, and 2.8.",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600&h=600&fit=crop",
    ],
    tags: ["bangle", "meenakari", "kundan", "set"],
  },
  {
    id: 102,
    name: "AD Tennis Bracelet",
    category: "Bracelet",
    subCategory: "Chain Bracelet",
    price: 1099,
    originalPrice: 1400,
    discount: 21,
    rating: 4.7,
    reviews: 38,
    stock: 14,
    isNew: false,
    isBestSeller: true,
    description: "Classic AD tennis bracelet with a continuous row of sparkling stones. Adjustable clasp fits most wrist sizes.",
    images: [
      "https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600&h=600&fit=crop",
    ],
    tags: ["bracelet", "AD", "tennis", "everyday"],
  },
  {
    id: 103,
    name: "Peacock Motif Bangle",
    category: "Bracelet",
    subCategory: "Bangle",
    price: 949,
    originalPrice: null,
    discount: 0,
    rating: 4.5,
    reviews: 16,
    stock: 9,
    isNew: true,
    isBestSeller: false,
    description: "Handcrafted peacock motif bangle in oxidised silver tone with multicolour AD stones. Inspired by traditional Indian art.",
    images: [
      "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600&h=600&fit=crop",
    ],
    tags: ["bangle", "AD", "peacock", "oxidised"],
  },
  {
    id: 104,
    name: "Kundan Kangan Pair",
    category: "Bracelet",
    subCategory: "Kangan",
    price: 1299,
    originalPrice: 1600,
    discount: 19,
    rating: 4.3,
    reviews: 18,
    stock: 8,
    isNew: false,
    isBestSeller: false,
    description: "A pair of Kundan kangan with adjustable screw clasp. Features floral Kundan motifs on a gold-plated base.",
    images: [
      "https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600&h=600&fit=crop",
    ],
    tags: ["kangan", "bracelet", "kundan"],
  },
  {
    id: 105,
    name: "Gold-Tone Charm Bracelet",
    category: "Bracelet",
    subCategory: "Chain Bracelet",
    price: 699,
    originalPrice: 950,
    discount: 26,
    rating: 4.2,
    reviews: 24,
    stock: 22,
    isNew: false,
    isBestSeller: false,
    description: "Delicate gold-tone chain bracelet with hanging charms including heart, star, and lotus. Lightweight everyday wear.",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop",
    ],
    tags: ["bracelet", "charm", "gold", "everyday"],
  },
  {
    id: 106,
    name: "Bridal Chooda Set — Red & White",
    category: "Bracelet",
    subCategory: "Chooda",
    price: 2499,
    originalPrice: 3000,
    discount: 17,
    rating: 4.9,
    reviews: 75,
    stock: 6,
    isNew: false,
    isBestSeller: true,
    description: "Traditional Punjabi bridal chooda set in red and white with gold foil detailing. Set of 21 bangles.",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=600&fit=crop",
    ],
    tags: ["chooda", "bridal", "punjabi", "bangle", "set"],
  },
  {
    id: 107,
    name: "Oxidised Silver Cuff Bracelet",
    category: "Bracelet",
    subCategory: "Cuff",
    price: 849,
    originalPrice: 1100,
    discount: 23,
    rating: 4.4,
    reviews: 21,
    stock: 17,
    isNew: true,
    isBestSeller: false,
    description: "Broad oxidised silver cuff bracelet with tribal floral engravings. Open-ended, fits most wrist sizes.",
    images: [
      "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600&h=600&fit=crop",
    ],
    tags: ["cuff", "oxidised", "silver", "tribal"],
  },
  {
    id: 108,
    name: "Pearl Beaded Bracelet",
    category: "Bracelet",
    subCategory: "Beaded",
    price: 549,
    originalPrice: 750,
    discount: 27,
    rating: 4.6,
    reviews: 33,
    stock: 28,
    isNew: false,
    isBestSeller: false,
    description: "Elastic pearl beaded bracelet with a gold-tone spacer bead. Stackable — looks great with 2-3 together.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["pearl", "beaded", "bracelet", "stackable"],
  },
  {
    id: 109,
    name: "Floral Lac Bangle Set (4 pcs)",
    category: "Bracelet",
    subCategory: "Bangle",
    price: 1199,
    originalPrice: 1500,
    discount: 20,
    rating: 4.7,
    reviews: 41,
    stock: 11,
    isNew: false,
    isBestSeller: false,
    description: "Colourful lac bangles with floral mirror work. Set of 4 in mixed shades of green and red. Rajasthani handcraft.",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=600&fit=crop",
    ],
    tags: ["lac", "bangle", "floral", "rajasthani"],
  },
  {
    id: 110,
    name: "Kundan Bracelet — Blue Stone",
    category: "Bracelet",
    subCategory: "Chain Bracelet",
    price: 999,
    originalPrice: 1300,
    discount: 23,
    rating: 4.5,
    reviews: 19,
    stock: 13,
    isNew: true,
    isBestSeller: false,
    description: "Elegant kundan bracelet featuring blue sapphire-coloured stones set in a gold-tone base. Ideal for festive wear.",
    images: [
      "https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600&h=600&fit=crop",
    ],
    tags: ["kundan", "bracelet", "blue", "sapphire"],
  },
  {
    id: 111,
    name: "Antique Kadaa Pair",
    category: "Bracelet",
    subCategory: "Kada",
    price: 1699,
    originalPrice: 2100,
    discount: 19,
    rating: 4.8,
    reviews: 29,
    stock: 7,
    isNew: false,
    isBestSeller: true,
    description: "Heavy antique gold-finish kadaa pair with embossed temple motifs. Worn as bridal or festive jewellery.",
    images: [
      "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600&h=600&fit=crop",
    ],
    tags: ["kada", "antique", "temple", "bridal"],
  },
  {
    id: 112,
    name: "Diamond-Cut Pola Bangle",
    category: "Bracelet",
    subCategory: "Bangle",
    price: 599,
    originalPrice: null,
    discount: 0,
    rating: 4.1,
    reviews: 14,
    stock: 30,
    isNew: false,
    isBestSeller: false,
    description: "Simple diamond-cut pola bangle in shiny gold-tone metal. Minimalist everyday accessory.",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop",
    ],
    tags: ["pola", "bangle", "minimalist", "diamond-cut"],
  },
  {
    id: 113,
    name: "Enamel Flower Bangle Set (3 pcs)",
    category: "Bracelet",
    subCategory: "Bangle",
    price: 899,
    originalPrice: 1200,
    discount: 25,
    rating: 4.4,
    reviews: 22,
    stock: 16,
    isNew: true,
    isBestSeller: false,
    description: "Set of 3 enamel-painted flower bangles in pastel tones. Fun, modern, and perfect for casual outings.",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=600&fit=crop",
    ],
    tags: ["enamel", "bangle", "flower", "pastel", "set"],
  },
  {
    id: 114,
    name: "Bridal Polki Bracelet",
    category: "Bracelet",
    subCategory: "Chain Bracelet",
    price: 2299,
    originalPrice: 2800,
    discount: 18,
    rating: 4.9,
    reviews: 47,
    stock: 5,
    isNew: false,
    isBestSeller: true,
    description: "Uncut polki stone bracelet with ruby and emerald accents on a 22kt gold-plated base. Bridal jewellery favourite.",
    images: [
      "https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600&h=600&fit=crop",
    ],
    tags: ["polki", "bridal", "bracelet", "ruby", "emerald"],
  },
  {
    id: 115,
    name: "Silver Ankle-to-Toe Chain",
    category: "Bracelet",
    subCategory: "Chain Bracelet",
    price: 449,
    originalPrice: 600,
    discount: 25,
    rating: 4.3,
    reviews: 17,
    stock: 25,
    isNew: false,
    isBestSeller: false,
    description: "Dainty ankle-to-toe chain bracelet in 92.5 silver-tone. Adjustable chain with floral toe ring end.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["anklet", "toe ring", "silver", "chain"],
  },

  // ══════════════════════════════════════════════════════
  // EARRINGS (15 items)
  // ══════════════════════════════════════════════════════
  {
    id: 201,
    name: "Chandbali Drop Earrings",
    category: "Earrings",
    subCategory: "Chandbali",
    price: 899,
    originalPrice: 1200,
    discount: 25,
    rating: 4.4,
    reviews: 31,
    stock: 25,
    isNew: false,
    isBestSeller: false,
    description: "Classic Chandbali-style drop earrings with Kundan stone setting and pearl drops. Lightweight and comfortable for all-day wear.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["earrings", "chandbali", "kundan", "drop"],
  },
  {
    id: 202,
    name: "Jhumka Earrings — Ruby Red",
    category: "Earrings",
    subCategory: "Jhumka",
    price: 749,
    originalPrice: 999,
    discount: 25,
    rating: 4.7,
    reviews: 56,
    stock: 30,
    isNew: false,
    isBestSeller: true,
    description: "Traditional jhumka earrings with ruby-red stone inlay and gold-tone metal. A festive favourite.",
    images: [
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&h=600&fit=crop",
    ],
    tags: ["jhumka", "earrings", "kundan", "ruby"],
  },
  {
    id: 203,
    name: "Temple Jewellery Long Earrings",
    category: "Earrings",
    subCategory: "Dangler",
    price: 1149,
    originalPrice: null,
    discount: 0,
    rating: 5.0,
    reviews: 5,
    stock: 10,
    isNew: true,
    isBestSeller: false,
    description: "South Indian temple jewellery style long earrings with deity motifs and ruby accents. Ideal for Bharatanatyam and classical events.",
    images: [
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&h=600&fit=crop",
    ],
    tags: ["temple", "earrings", "classical", "dangler"],
  },
  {
    id: 204,
    name: "Pearl Stud Earrings",
    category: "Earrings",
    subCategory: "Studs",
    price: 449,
    originalPrice: 600,
    discount: 25,
    rating: 4.6,
    reviews: 68,
    stock: 45,
    isNew: false,
    isBestSeller: true,
    description: "Simple and elegant freshwater pearl studs with gold-tone push-back. Perfect for daily and office wear.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["pearl", "studs", "everyday", "office"],
  },
  {
    id: 205,
    name: "Oxidised Peacock Jhumka",
    category: "Earrings",
    subCategory: "Jhumka",
    price: 699,
    originalPrice: 900,
    discount: 22,
    rating: 4.5,
    reviews: 42,
    stock: 20,
    isNew: false,
    isBestSeller: false,
    description: "Oxidised silver peacock-shaped jhumka with blue and green enamel. Bohemian style meets Indian tradition.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["jhumka", "peacock", "oxidised", "enamel"],
  },
  {
    id: 206,
    name: "Hoop Earrings — Gold Plated",
    category: "Earrings",
    subCategory: "Hoops",
    price: 549,
    originalPrice: 750,
    discount: 27,
    rating: 4.3,
    reviews: 37,
    stock: 32,
    isNew: false,
    isBestSeller: false,
    description: "Medium-sized gold-plated hoop earrings with a smooth finish. Minimalist and versatile for any occasion.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["hoops", "gold", "minimalist", "everyday"],
  },
  {
    id: 207,
    name: "Kundan Long Tassel Earrings",
    category: "Earrings",
    subCategory: "Tassel",
    price: 1299,
    originalPrice: 1600,
    discount: 19,
    rating: 4.8,
    reviews: 28,
    stock: 12,
    isNew: true,
    isBestSeller: false,
    description: "Dramatic tassel earrings with a Kundan-studded top and long gold-thread tassels. Statement piece for weddings.",
    images: [
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&h=600&fit=crop",
    ],
    tags: ["tassel", "kundan", "earrings", "wedding"],
  },
  {
    id: 208,
    name: "Emerald AD Drop Earrings",
    category: "Earrings",
    subCategory: "Dangler",
    price: 999,
    originalPrice: 1300,
    discount: 23,
    rating: 4.6,
    reviews: 19,
    stock: 15,
    isNew: false,
    isBestSeller: false,
    description: "Emerald green AD stone drop earrings with an intricate gold-tone filigree frame. Festive and bridal friendly.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["AD", "emerald", "drop", "festive"],
  },
  {
    id: 209,
    name: "Floral Meenakari Studs",
    category: "Earrings",
    subCategory: "Studs",
    price: 399,
    originalPrice: 550,
    discount: 27,
    rating: 4.4,
    reviews: 53,
    stock: 38,
    isNew: false,
    isBestSeller: true,
    description: "Small round Meenakari stud earrings with multicolour enamel floral design. Comfortable screw back.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["meenakari", "studs", "floral", "enamel"],
  },
  {
    id: 210,
    name: "Bahubali Statement Earrings",
    category: "Earrings",
    subCategory: "Chandbali",
    price: 1599,
    originalPrice: 2000,
    discount: 20,
    rating: 4.9,
    reviews: 84,
    stock: 8,
    isNew: false,
    isBestSeller: true,
    description: "Large Bahubali-style statement earrings with layered Kundan design and pearl drops. Bridal showstopper.",
    images: [
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&h=600&fit=crop",
    ],
    tags: ["bahubali", "earrings", "bridal", "kundan"],
  },
  {
    id: 211,
    name: "Tribal Boho Earrings",
    category: "Earrings",
    subCategory: "Dangler",
    price: 599,
    originalPrice: null,
    discount: 0,
    rating: 4.2,
    reviews: 16,
    stock: 19,
    isNew: true,
    isBestSeller: false,
    description: "Boho-style tribal earrings with wooden beads, oxidised metal, and feather-like dangles. Casual and artistic.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["tribal", "boho", "earrings", "casual"],
  },
  {
    id: 212,
    name: "Diamond-Shape AD Ear Cuff",
    category: "Earrings",
    subCategory: "Ear Cuff",
    price: 699,
    originalPrice: 900,
    discount: 22,
    rating: 4.5,
    reviews: 12,
    stock: 20,
    isNew: true,
    isBestSeller: false,
    description: "Non-piercing AD stone ear cuff in a geometric diamond shape. Trendy modern design for the fashion-forward.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["ear cuff", "AD", "geometric", "modern"],
  },
  {
    id: 213,
    name: "Gold Filigree Drop Earrings",
    category: "Earrings",
    subCategory: "Dangler",
    price: 849,
    originalPrice: 1100,
    discount: 23,
    rating: 4.7,
    reviews: 26,
    stock: 14,
    isNew: false,
    isBestSeller: false,
    description: "Intricate filigree gold-tone drop earrings with a teardrop silhouette. Elegant enough for weddings, light enough for everyday.",
    images: [
      "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&h=600&fit=crop",
    ],
    tags: ["filigree", "gold", "drop", "everyday"],
  },
  {
    id: 214,
    name: "Kundan Maatapatti Earrings",
    category: "Earrings",
    subCategory: "Maatapatti",
    price: 1399,
    originalPrice: 1800,
    discount: 22,
    rating: 4.8,
    reviews: 33,
    stock: 9,
    isNew: false,
    isBestSeller: true,
    description: "Maatapatti earrings that connect to a forehead chain. Kundan-studded with green emerald stone accents.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["maatapatti", "kundan", "bridal", "forehead"],
  },
  {
    id: 215,
    name: "Layered Fringe Earrings",
    category: "Earrings",
    subCategory: "Dangler",
    price: 799,
    originalPrice: 1000,
    discount: 20,
    rating: 4.3,
    reviews: 21,
    stock: 18,
    isNew: true,
    isBestSeller: false,
    description: "Gold-tone layered fringe earrings with AD stone tops and cascading metal strips. Modern take on traditional design.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["fringe", "layered", "AD", "modern"],
  },

  // ══════════════════════════════════════════════════════
  // NECKLACE (15 items)
  // ══════════════════════════════════════════════════════
  {
    id: 301,
    name: "Royal Kundan Necklace Set",
    category: "Necklace",
    subCategory: "Kundan",
    price: 2499,
    originalPrice: 3200,
    discount: 22,
    rating: 5.0,
    reviews: 48,
    stock: 12,
    isNew: true,
    isBestSeller: false,
    description: "Handcrafted royal Kundan necklace set with intricate gold-tone work and semi-precious stones. Perfect for weddings and festive occasions.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop",
    ],
    tags: ["bridal", "wedding", "kundan", "necklace"],
  },
  {
    id: 302,
    name: "Layered Kundan Haar",
    category: "Necklace",
    subCategory: "Haar",
    price: 3199,
    originalPrice: 4000,
    discount: 20,
    rating: 4.5,
    reviews: 34,
    stock: 7,
    isNew: false,
    isBestSeller: true,
    description: "Three-layered Kundan haar with Meenakari detailing and matching earrings. A timeless bridal jewellery piece.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["bridal", "haar", "kundan", "layered"],
  },
  {
    id: 303,
    name: "Polki Stone Choker",
    category: "Necklace",
    subCategory: "Choker",
    price: 1899,
    originalPrice: null,
    discount: 0,
    rating: 4.8,
    reviews: 27,
    stock: 15,
    isNew: true,
    isBestSeller: false,
    description: "Elegant polki stone choker necklace with a velvet finish backing. Pairs beautifully with sarees and lehengas.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["choker", "polki", "kundan"],
  },
  {
    id: 304,
    name: "Antique Gold Layered Necklace",
    category: "Necklace",
    subCategory: "Layered",
    price: 2199,
    originalPrice: null,
    discount: 0,
    rating: 4.8,
    reviews: 8,
    stock: 5,
    isNew: true,
    isBestSeller: false,
    description: "Newly launched antique gold-finish layered necklace with coin and bead detailing. Limited stock available.",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop",
    ],
    tags: ["new", "necklace", "antique", "layered"],
  },
  {
    id: 305,
    name: "Pearl & Kundan Pendant Necklace",
    category: "Necklace",
    subCategory: "Kundan",
    price: 1799,
    originalPrice: 2300,
    discount: 22,
    rating: 4.7,
    reviews: 39,
    stock: 11,
    isNew: false,
    isBestSeller: true,
    description: "Single-strand pearl necklace with a Kundan centrepiece pendant. Elegant and versatile for casual and formal wear.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["pearl", "kundan", "necklace", "pendant"],
  },
  {
    id: 306,
    name: "Meenakari Necklace Set",
    category: "Necklace",
    subCategory: "Set",
    price: 2099,
    originalPrice: 2600,
    discount: 19,
    rating: 4.6,
    reviews: 22,
    stock: 8,
    isNew: false,
    isBestSeller: false,
    description: "Full Meenakari necklace set with earrings featuring vivid blue and green enamel on a gold-tone base.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["meenakari", "necklace", "set", "enamel"],
  },
  {
    id: 307,
    name: "AD Choker Necklace — Emerald",
    category: "Necklace",
    subCategory: "Choker",
    price: 1599,
    originalPrice: 2000,
    discount: 20,
    rating: 4.9,
    reviews: 51,
    stock: 9,
    isNew: false,
    isBestSeller: true,
    description: "Emerald green AD stone choker necklace with a close-fitting velvet base. Pairs with both contemporary and traditional outfits.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["AD", "choker", "emerald", "bridal"],
  },
  {
    id: 308,
    name: "Temple Gold Necklace",
    category: "Necklace",
    subCategory: "Temple",
    price: 2799,
    originalPrice: 3500,
    discount: 20,
    rating: 4.8,
    reviews: 44,
    stock: 6,
    isNew: false,
    isBestSeller: true,
    description: "South Indian temple necklace with Lakshmi pendant and ruby-red stone detailing. Heavy, grand, and wedding-ready.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["temple", "necklace", "gold", "Lakshmi", "bridal"],
  },
  {
    id: 309,
    name: "Floral Rani Haar",
    category: "Necklace",
    subCategory: "Haar",
    price: 3599,
    originalPrice: 4500,
    discount: 20,
    rating: 4.9,
    reviews: 29,
    stock: 4,
    isNew: false,
    isBestSeller: true,
    description: "Long floral Rani Haar with gold beads and floral Kundan motifs. Drapes elegantly to the waist.",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop",
    ],
    tags: ["rani haar", "long", "kundan", "bridal"],
  },
  {
    id: 310,
    name: "Minimalist Gold Chain Necklace",
    category: "Necklace",
    subCategory: "Chain",
    price: 799,
    originalPrice: 1000,
    discount: 20,
    rating: 4.4,
    reviews: 60,
    stock: 35,
    isNew: false,
    isBestSeller: false,
    description: "Slim, dainty gold-tone chain necklace with a tiny star pendant. Your go-to everyday layering piece.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["minimalist", "chain", "everyday", "layering"],
  },
  {
    id: 311,
    name: "Beaded Tribal Necklace",
    category: "Necklace",
    subCategory: "Beaded",
    price: 699,
    originalPrice: null,
    discount: 0,
    rating: 4.3,
    reviews: 18,
    stock: 22,
    isNew: true,
    isBestSeller: false,
    description: "Handmade tribal necklace with wooden beads, oxidised metal discs, and turquoise stone accents.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["tribal", "beaded", "oxidised", "turquoise"],
  },
  {
    id: 312,
    name: "Bridal Polki Necklace Set",
    category: "Necklace",
    subCategory: "Set",
    price: 4999,
    originalPrice: 6000,
    discount: 17,
    rating: 5.0,
    reviews: 31,
    stock: 3,
    isNew: false,
    isBestSeller: true,
    description: "Premium uncut polki bridal necklace set with earrings. Heavy 22kt gold-plated setting with ruby and emerald inlay.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["polki", "bridal", "set", "premium"],
  },
  {
    id: 313,
    name: "Oxidised Lotus Pendant Necklace",
    category: "Necklace",
    subCategory: "Pendant",
    price: 649,
    originalPrice: 850,
    discount: 24,
    rating: 4.5,
    reviews: 45,
    stock: 27,
    isNew: false,
    isBestSeller: false,
    description: "Oxidised silver lotus pendant on a delicate chain. Symbolic and stylish — great as a gift.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["pendant", "lotus", "oxidised", "gift"],
  },
  {
    id: 314,
    name: "Ruby AD Statement Necklace",
    category: "Necklace",
    subCategory: "Statement",
    price: 1999,
    originalPrice: 2500,
    discount: 20,
    rating: 4.7,
    reviews: 23,
    stock: 10,
    isNew: true,
    isBestSeller: false,
    description: "Bold ruby-red AD stone statement necklace with a wide collar design. Perfect for reception and cocktail parties.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["ruby", "AD", "statement", "collar"],
  },
  {
    id: 315,
    name: "Jadau Long Necklace",
    category: "Necklace",
    subCategory: "Haar",
    price: 3299,
    originalPrice: 4200,
    discount: 21,
    rating: 4.8,
    reviews: 17,
    stock: 5,
    isNew: false,
    isBestSeller: false,
    description: "Jadau long necklace with hand-set precious stone look tiles. Traditional Rajasthani craft with a regal finish.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["jadau", "long", "rajasthani", "bridal"],
  },

  // ══════════════════════════════════════════════════════
  // MANGALSUTRA (12 items)
  // ══════════════════════════════════════════════════════
  {
    id: 401,
    name: "Classic Black Bead Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Traditional",
    price: 1299,
    originalPrice: 1600,
    discount: 19,
    rating: 4.9,
    reviews: 112,
    stock: 20,
    isNew: false,
    isBestSeller: true,
    description: "Traditional two-strand black bead mangalsutra with a gold-tone pendant. 18-inch adjustable chain.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["mangalsutra", "black bead", "traditional", "wedding"],
  },
  {
    id: 402,
    name: "Diamond-Look AD Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Modern",
    price: 1799,
    originalPrice: 2200,
    discount: 18,
    rating: 4.8,
    reviews: 67,
    stock: 15,
    isNew: false,
    isBestSeller: true,
    description: "Contemporary AD diamond-look mangalsutra with a sleek single-strand design. Perfect for the modern bride.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["mangalsutra", "AD", "modern", "diamond"],
  },
  {
    id: 403,
    name: "Gold-Plated Tanmaniya",
    category: "Mangalsutra",
    subCategory: "Tanmaniya",
    price: 999,
    originalPrice: 1300,
    discount: 23,
    rating: 4.6,
    reviews: 44,
    stock: 18,
    isNew: false,
    isBestSeller: false,
    description: "Lightweight Tanmaniya mangalsutra with a small round pendant. Ideal for daily wear — won't feel heavy.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["tanmaniya", "mangalsutra", "daily wear", "gold"],
  },
  {
    id: 404,
    name: "Maharashtrian Vati Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Regional",
    price: 1499,
    originalPrice: 1900,
    discount: 21,
    rating: 4.7,
    reviews: 38,
    stock: 10,
    isNew: false,
    isBestSeller: false,
    description: "Traditional Maharashtrian vati-design mangalsutra with gold-tone hollow oval pendants on a black bead chain.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["maharashtrian", "vati", "mangalsutra", "regional"],
  },
  {
    id: 405,
    name: "Floral Pendant Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Designer",
    price: 2099,
    originalPrice: 2600,
    discount: 19,
    rating: 4.8,
    reviews: 29,
    stock: 8,
    isNew: true,
    isBestSeller: false,
    description: "Designer mangalsutra with a floral Kundan pendant on a black-and-gold chain. Fusion of traditional and modern.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["floral", "kundan", "designer", "mangalsutra"],
  },
  {
    id: 406,
    name: "Short Mangalsutra — Dainty Style",
    category: "Mangalsutra",
    subCategory: "Modern",
    price: 899,
    originalPrice: 1100,
    discount: 18,
    rating: 4.5,
    reviews: 55,
    stock: 25,
    isNew: false,
    isBestSeller: true,
    description: "Short 14-inch dainty mangalsutra with minimal beads and a tiny heart-shaped pendant. Discreet and elegant.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["short", "dainty", "heart", "mangalsutra", "modern"],
  },
  {
    id: 407,
    name: "Ruby Stone Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Designer",
    price: 1699,
    originalPrice: 2100,
    discount: 19,
    rating: 4.7,
    reviews: 20,
    stock: 12,
    isNew: true,
    isBestSeller: false,
    description: "Elegant mangalsutra with a ruby AD stone centre pendant flanked by small Kundan accents. Rich festive look.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["ruby", "kundan", "mangalsutra", "festive"],
  },
  {
    id: 408,
    name: "Double Strand Long Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Traditional",
    price: 1399,
    originalPrice: 1800,
    discount: 22,
    rating: 4.6,
    reviews: 33,
    stock: 9,
    isNew: false,
    isBestSeller: false,
    description: "Classic double-strand long mangalsutra (24-inch) with traditional gold pendant and black beads throughout.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["double strand", "long", "traditional", "mangalsutra"],
  },
  {
    id: 409,
    name: "Minimalist Bar Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Modern",
    price: 749,
    originalPrice: 1000,
    discount: 25,
    rating: 4.4,
    reviews: 47,
    stock: 30,
    isNew: false,
    isBestSeller: false,
    description: "Ultra-modern bar-shaped gold-tone pendant mangalsutra. Barely looks like one — ideal for corporate wear.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["bar", "minimalist", "modern", "mangalsutra", "office"],
  },
  {
    id: 410,
    name: "Carved Temple Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Temple",
    price: 2299,
    originalPrice: 2800,
    discount: 18,
    rating: 4.9,
    reviews: 24,
    stock: 6,
    isNew: false,
    isBestSeller: true,
    description: "Intricately carved temple-design gold-plated mangalsutra with deity motifs. Traditional South Indian style.",
    images: [
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&h=600&fit=crop",
    ],
    tags: ["temple", "carved", "south indian", "mangalsutra"],
  },
  {
    id: 411,
    name: "Reversible Locket Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Modern",
    price: 1099,
    originalPrice: null,
    discount: 0,
    rating: 4.5,
    reviews: 16,
    stock: 14,
    isNew: true,
    isBestSeller: false,
    description: "Innovative reversible locket mangalsutra — deity motif on one side, plain heart on the other. Two looks in one.",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&h=600&fit=crop",
    ],
    tags: ["reversible", "locket", "mangalsutra", "modern"],
  },
  {
    id: 412,
    name: "Emerald Drop Mangalsutra",
    category: "Mangalsutra",
    subCategory: "Designer",
    price: 1899,
    originalPrice: 2400,
    discount: 21,
    rating: 4.7,
    reviews: 19,
    stock: 7,
    isNew: true,
    isBestSeller: false,
    description: "Designer mangalsutra with cascading emerald drop pendants alternating with gold beads. Wedding collection exclusive.",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&h=600&fit=crop",
    ],
    tags: ["emerald", "drop", "designer", "mangalsutra"],
  },

  // ══════════════════════════════════════════════════════
  // HAIR ACCESSORIES (12 items)
  // ══════════════════════════════════════════════════════
  {
    id: 501,
    name: "Maang Tikka — Gold Finish",
    category: "Hair Accessories",
    subCategory: "Maang Tikka",
    price: 649,
    originalPrice: 850,
    discount: 24,
    rating: 4.4,
    reviews: 19,
    stock: 20,
    isNew: true,
    isBestSeller: false,
    description: "Adjustable chain maang tikka with a circular Kundan centrepiece. Fits all head sizes. Great for bridal and party wear.",
    images: [
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&h=600&fit=crop",
    ],
    tags: ["maangtikka", "hair", "kundan", "bridal"],
  },
  {
    id: 502,
    name: "Passa Side Headpiece",
    category: "Hair Accessories",
    subCategory: "Passa",
    price: 849,
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviews: 11,
    stock: 6,
    isNew: true,
    isBestSeller: false,
    description: "Bridal Passa with cascading Kundan danglers. Worn on the side of the head, pairs beautifully with a dupatta.",
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&h=600&fit=crop",
    ],
    tags: ["passa", "hair", "kundan", "bridal"],
  },
  {
    id: 503,
    name: "AD Juda Pin Set (2 pcs)",
    category: "Hair Accessories",
    subCategory: "Juda Pin",
    price: 399,
    originalPrice: 550,
    discount: 27,
    rating: 4.3,
    reviews: 29,
    stock: 40,
    isNew: false,
    isBestSeller: false,
    description: "Set of 2 decorative juda pins with AD stone flowers. Secure your bun in style at weddings or casual outings.",
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&h=600&fit=crop",
    ],
    tags: ["judapin", "hair", "AD", "set"],
  },
  {
    id: 504,
    name: "Floral Kundan Mathapatti",
    category: "Hair Accessories",
    subCategory: "Mathapatti",
    price: 1299,
    originalPrice: 1600,
    discount: 19,
    rating: 4.8,
    reviews: 35,
    stock: 8,
    isNew: false,
    isBestSeller: true,
    description: "Full forehead mathapatti with floral Kundan motifs. Covers the entire hairline. Bridal essential.",
    images: [
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&h=600&fit=crop",
    ],
    tags: ["mathapatti", "kundan", "bridal", "forehead"],
  },
  {
    id: 505,
    name: "Pearl Bridal Hair Clip (2 pcs)",
    category: "Hair Accessories",
    subCategory: "Hair Clip",
    price: 299,
    originalPrice: 450,
    discount: 34,
    rating: 4.2,
    reviews: 43,
    stock: 50,
    isNew: false,
    isBestSeller: false,
    description: "U-shaped pearl-studded hair clip. Works with updos, braids, or loose hair. Pack of 2.",
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&h=600&fit=crop",
    ],
    tags: ["hairclip", "pearl", "bridal", "updo"],
  },
  {
    id: 506,
    name: "Kundan Bridal Tikka — Round",
    category: "Hair Accessories",
    subCategory: "Maang Tikka",
    price: 999,
    originalPrice: 1300,
    discount: 23,
    rating: 4.7,
    reviews: 27,
    stock: 12,
    isNew: false,
    isBestSeller: true,
    description: "Large round Kundan tikka with ruby drop. Makes a dramatic impact for bridal photography.",
    images: [
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&h=600&fit=crop",
    ],
    tags: ["tikka", "round", "kundan", "bridal"],
  },
  {
    id: 507,
    name: "Floral Hair Brooch",
    category: "Hair Accessories",
    subCategory: "Brooch",
    price: 349,
    originalPrice: null,
    discount: 0,
    rating: 4.1,
    reviews: 15,
    stock: 30,
    isNew: true,
    isBestSeller: false,
    description: "Small floral gold-tone brooch that pins to a saree pleat or hair bun. Versatile accessory.",
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&h=600&fit=crop",
    ],
    tags: ["brooch", "floral", "hair", "saree"],
  },
  {
    id: 508,
    name: "Boho Feather Headband",
    category: "Hair Accessories",
    subCategory: "Headband",
    price: 449,
    originalPrice: 600,
    discount: 25,
    rating: 4.3,
    reviews: 22,
    stock: 18,
    isNew: false,
    isBestSeller: false,
    description: "Boho-style wide headband with metal leaf and feather motifs. Elastic band for comfortable fit.",
    images: [
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&h=600&fit=crop",
    ],
    tags: ["headband", "boho", "feather", "casual"],
  },
  {
    id: 509,
    name: "Beaded Haath Phool",
    category: "Hair Accessories",
    subCategory: "Haath Phool",
    price: 699,
    originalPrice: 900,
    discount: 22,
    rating: 4.5,
    reviews: 19,
    stock: 14,
    isNew: false,
    isBestSeller: false,
    description: "Beaded haath phool connecting a finger ring to a wrist chain. Bridal and mehendi ceremony staple.",
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&h=600&fit=crop",
    ],
    tags: ["haathphool", "bridal", "beaded", "mehendi"],
  },
  {
    id: 510,
    name: "Antique Haar Pin Set (4 pcs)",
    category: "Hair Accessories",
    subCategory: "Juda Pin",
    price: 599,
    originalPrice: 800,
    discount: 25,
    rating: 4.4,
    reviews: 31,
    stock: 22,
    isNew: false,
    isBestSeller: false,
    description: "Set of 4 antique gold-tone haar pins with floral tips. Mix and match with any hairstyle.",
    images: [
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&h=600&fit=crop",
    ],
    tags: ["haarpin", "antique", "floral", "set"],
  },
  {
    id: 511,
    name: "Kundan Sheeshphool",
    category: "Hair Accessories",
    subCategory: "Sheeshphool",
    price: 1099,
    originalPrice: 1400,
    discount: 21,
    rating: 4.7,
    reviews: 23,
    stock: 7,
    isNew: true,
    isBestSeller: false,
    description: "Traditional Kundan sheeshphool — a full crown-like hair ornament. Worn by brides for the wedding ceremony.",
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&h=600&fit=crop",
    ],
    tags: ["sheeshphool", "kundan", "bridal", "crown"],
  },
  {
    id: 512,
    name: "Crystal Hair Vine",
    category: "Hair Accessories",
    subCategory: "Hair Vine",
    price: 799,
    originalPrice: 1050,
    discount: 24,
    rating: 4.6,
    reviews: 17,
    stock: 10,
    isNew: true,
    isBestSeller: false,
    description: "Flexible crystal hair vine that can be twisted into any hairstyle. Works for both western and Indian looks.",
    images: [
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=600&h=600&fit=crop",
    ],
    tags: ["crystal", "vine", "hair", "flexible", "bridal"],
  },

  // ══════════════════════════════════════════════════════
  // RINGS (13 items)
  // ══════════════════════════════════════════════════════
  {
    id: 601,
    name: "AD Floral Finger Ring",
    category: "Rings",
    subCategory: "Casual",
    price: 499,
    originalPrice: 699,
    discount: 29,
    rating: 4.2,
    reviews: 22,
    stock: 35,
    isNew: false,
    isBestSeller: false,
    description: "Delicate AD stone floral ring with rhodium plating. A perfect everyday accessory or gifting option.",
    images: [
      "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600&h=600&fit=crop",
    ],
    tags: ["ring", "AD", "floral", "everyday"],
  },
  {
    id: 602,
    name: "Cocktail Statement Ring",
    category: "Rings",
    subCategory: "Statement",
    price: 799,
    originalPrice: 1100,
    discount: 27,
    rating: 4.9,
    reviews: 44,
    stock: 18,
    isNew: false,
    isBestSeller: true,
    description: "Bold cocktail ring with large AD stone in a vintage gold-tone setting. Turns heads at every party.",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=600&fit=crop",
    ],
    tags: ["ring", "AD", "cocktail", "party"],
  },
  {
    id: 603,
    name: "Kundan Bridal Ring Set (5 pcs)",
    category: "Rings",
    subCategory: "Bridal",
    price: 1499,
    originalPrice: 1900,
    discount: 21,
    rating: 4.8,
    reviews: 37,
    stock: 10,
    isNew: false,
    isBestSeller: true,
    description: "Set of 5 Kundan rings — includes a statement piece and 4 stackable bands. Bridal finger accessories.",
    images: [
      "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600&h=600&fit=crop",
    ],
    tags: ["kundan", "ring", "bridal", "set", "stackable"],
  },
  {
    id: 604,
    name: "Oxidised Thumb Ring",
    category: "Rings",
    subCategory: "Thumb Ring",
    price: 349,
    originalPrice: 500,
    discount: 30,
    rating: 4.4,
    reviews: 28,
    stock: 32,
    isNew: false,
    isBestSeller: false,
    description: "Broad oxidised silver thumb ring with tribal floral engraving. Adjustable size — fits most thumb sizes.",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=600&fit=crop",
    ],
    tags: ["thumb ring", "oxidised", "tribal", "adjustable"],
  },
  {
    id: 605,
    name: "Emerald Solitaire Ring",
    category: "Rings",
    subCategory: "Solitaire",
    price: 999,
    originalPrice: 1300,
    discount: 23,
    rating: 4.7,
    reviews: 19,
    stock: 15,
    isNew: true,
    isBestSeller: false,
    description: "Single emerald AD stone solitaire ring in a six-prong gold-tone setting. Looks like fine jewellery.",
    images: [
      "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600&h=600&fit=crop",
    ],
    tags: ["solitaire", "emerald", "AD", "ring"],
  },
  {
    id: 606,
    name: "Stackable Band Ring Set (5 pcs)",
    category: "Rings",
    subCategory: "Stackable",
    price: 849,
    originalPrice: 1100,
    discount: 23,
    rating: 4.5,
    reviews: 52,
    stock: 28,
    isNew: false,
    isBestSeller: true,
    description: "Set of 5 thin stackable bands — mixed finishes of gold, rose gold, and silver. Mix and match freely.",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=600&fit=crop",
    ],
    tags: ["stackable", "band", "ring", "set", "minimalist"],
  },
  {
    id: 607,
    name: "Toe Ring Pair — Silver",
    category: "Rings",
    subCategory: "Toe Ring",
    price: 299,
    originalPrice: 400,
    discount: 25,
    rating: 4.3,
    reviews: 61,
    stock: 50,
    isNew: false,
    isBestSeller: false,
    description: "Open-ended silver-tone toe ring pair with floral motif. Adjustable to fit any toe. Traditional bridal wear.",
    images: [
      "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600&h=600&fit=crop",
    ],
    tags: ["toe ring", "silver", "bridal", "floral"],
  },
  {
    id: 608,
    name: "Kundan Adjustable Ring",
    category: "Rings",
    subCategory: "Casual",
    price: 449,
    originalPrice: 600,
    discount: 25,
    rating: 4.4,
    reviews: 35,
    stock: 40,
    isNew: false,
    isBestSeller: false,
    description: "Adjustable Kundan ring with a teardrop stone in centre and small accents around. Fits sizes 5-9.",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=600&fit=crop",
    ],
    tags: ["kundan", "ring", "adjustable", "teardrop"],
  },
  {
    id: 609,
    name: "Ruby Floral Cocktail Ring",
    category: "Rings",
    subCategory: "Statement",
    price: 1199,
    originalPrice: 1500,
    discount: 20,
    rating: 4.8,
    reviews: 26,
    stock: 11,
    isNew: true,
    isBestSeller: false,
    description: "Oversized ruby floral ring with pave-set AD petals and a large centre stone. Show-stopping party piece.",
    images: [
      "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600&h=600&fit=crop",
    ],
    tags: ["ruby", "cocktail", "floral", "statement", "ring"],
  },
  {
    id: 610,
    name: "Polki Bridal Ring",
    category: "Rings",
    subCategory: "Bridal",
    price: 1899,
    originalPrice: 2400,
    discount: 21,
    rating: 4.9,
    reviews: 18,
    stock: 6,
    isNew: false,
    isBestSeller: true,
    description: "Uncut polki stone bridal ring with surrounding Kundan and emerald work. Pairs with polki necklace set.",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=600&fit=crop",
    ],
    tags: ["polki", "bridal", "ring", "kundan", "emerald"],
  },
  {
    id: 611,
    name: "Meenakari Enamel Ring",
    category: "Rings",
    subCategory: "Casual",
    price: 399,
    originalPrice: 550,
    discount: 27,
    rating: 4.3,
    reviews: 30,
    stock: 25,
    isNew: false,
    isBestSeller: false,
    description: "Colourful Meenakari enamel ring with a round motif top. Vibrant and cheerful for casual everyday wear.",
    images: [
      "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600&h=600&fit=crop",
    ],
    tags: ["meenakari", "enamel", "ring", "casual"],
  },
  {
    id: 612,
    name: "Half-Finger Midi Ring Set (3 pcs)",
    category: "Rings",
    subCategory: "Midi Ring",
    price: 549,
    originalPrice: 750,
    discount: 27,
    rating: 4.4,
    reviews: 24,
    stock: 20,
    isNew: true,
    isBestSeller: false,
    description: "Set of 3 half-finger midi rings in rose gold tone. Stack them together or wear individually for a trendy look.",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=600&fit=crop",
    ],
    tags: ["midi ring", "half finger", "rose gold", "set"],
  },
  {
    id: 613,
    name: "Elephant Temple Statement Ring",
    category: "Rings",
    subCategory: "Statement",
    price: 649,
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviews: 14,
    stock: 16,
    isNew: true,
    isBestSeller: false,
    description: "Statement ring shaped as a detailed elephant head — a symbol of luck and prosperity. Oxidised gold finish.",
    images: [
      "https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=600&h=600&fit=crop",
    ],
    tags: ["elephant", "temple", "statement", "ring", "oxidised"],
  },
];

// ══════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ══════════════════════════════════════════════════════

export const getByCategory = (category) =>
  products.filter((p) => p.category === category);

export const getBySubCategory = (subCategory) =>
  products.filter((p) => p.subCategory === subCategory);

export const getBestSellers = () =>
  products.filter((p) => p.isBestSeller);

export const getNewArrivals = () => {
  return products.filter((p) => p.isNew);
}

export const getById = (id) =>
  products.find((p) => p.id === Number(id));

export const searchProducts = (query) => {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
};

export const getDiscounted = () =>
  products.filter((p) => p.discount > 0).sort((a, b) => b.discount - a.discount);

export const getSortedByPrice = (order = "asc") =>
  [...products].sort((a, b) =>
    order === "asc" ? a.price - b.price : b.price - a.price
  );

export const getSortedByRating = () =>
  [...products].sort((a, b) => b.rating - a.rating);

export const CATEGORIES = [
  "Bracelet",
  "Earrings",
  "Necklace",
  "Mangalsutra",
  "Hair Accessories",
  "Rings",
];
